=== alexmsomarriba/TB-Syntosa-Validation/TeamBond.Syntosa.Validation/Tools/TeamBond.Syntosa.Validation.JsonToSyntosa/Services/Element.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Element",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "alias": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "domainUId": {
      "type": "string"
    },
    "isActive": {
      "type": "boolean"
    },
    "isAutoCollect": {
      "type": "boolean"
    },
    "isBuiltIn": {
      "type": "boolean"
    },
    "modifiedBy": {
      "type": "string"
    },
    "moduleUId": {
      "type": "string"
    },
    "moduleRecordUId": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "parentUId": {
      "type": "string"
    },
    "typeItemUId": {
      "type": "string"
    },
    "typeUIdRecordStatus": {
      "type": "string"
    },
    "uId": {
      "type": "string"
    },
    "elementEdges": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ElementEdge"
      }
    },
    "globalPropertyEdges": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/GlobalPropertyEdge"
      }
    },
    "globalPropertyList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/GlobalPropertyList"
      }
    },
    "privatePropertyEdges": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/PrivatePropertyEdge"
      }
    },
    "privatePropertyKeys": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/PrivatePropertyKey"
      }
    },
    "privateProperties": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/PrivateProperty"
      }
    }
  },
  "required": [ "description", "domainUId", "isActive", "alias", "isAutoCollect", "moduleUId", "moduleRecordUId", "typeUIdRecordStatus", "typeItemUId", "modifiedBy" ],
  "definitions": {
    "EdgeProperty": {
      "type": "object",
      "properties": {
        "attribute": {
          "type": "string"
        },
        "edgeTypeUId": {
          "type": "string"
        },
        "edgeUId": {
          "type": "string"
        },
        "modifiedBy": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "typeItemUId": {
          "type": "string"
        },
        "uId": {
          "type": "string"
        }
      },
      "required": [ "edgeTypeUId", "modifiedBy", "typeItemUId", "attribute" ]
    },
    "ElementEdge": {
      "type": "object",
      "properties": {
        "edgeProperties": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/EdgeProperty"
          }
        },
        "labelUId": {
          "type": "string"
        },
        "modifiedBy": {
          "type": "string"
        },
        "sourceElementUId": {
          "type": "string"
        },
        "targetElementUId": {
          "type": "string"
        },
        "typeItemUId": {
          "type": "string"
        },
        "UId": {
          "type": "string"
        }
      },
      "required": [ "sourceElementUId", "targetElementUId", "modifiedBy", "typeItemUId" ]
    },
    "GlobalPropertyEdgeProperty": {
      "type": "object",
      "properties": {
        "attribute": {
          "type": "string"
        },
        "edgeUId": {
          "type": "string"
        },
        "modifiedBy": {
          "type": "string"
        },
        "typeItemUId": {
          "type": "string"
        },
        "uId": {
          "type": "string"
        }
      },
      "required": [ "edgeUId", "modifiedBy", "typeItemUId", "attribute" ]
    },
    "GlobalPropertyEdge": {
      "type": "object",
      "properties": {
        "elementUId": {
          "type": "string"
        },
        "globalPropertyEdgeProperties": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GlobalPropertyEdgeProperty"
          }
        },
        "globalPropertyUId": {
          "type": "string"
        },
        "isElementDriver": {
          "type": "boolean"
        },
        "modifiedBy": {
          "type": "string"
        },
        "typeItemUId": {
          "type": "string"
        },
        "uId": {
          "type": "string"
        }
      },
      "required": [ "elementUId", "globalPropertyUId", "isElementDriver", "modifiedBy", "typeItemUId" ]
    },
    "GlobalPropertyList": {
      "type": "object",
      "properties": {
        "attribute": {
          "type": "string"
        },
        "elementUId": {
          "type": "string"
        },
        "isAutoCollect": {
          "type": "boolean"
        },
        "isActive": {
          "type": "boolean"
        },
        "modifiedBy": {
          "type": "string"
        },
        "moduleUIdAutoCollect": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "sortOrder": {
          "type": "integer"
        },
        "typeItemUId": {
          "type": "string"
        },
        "uId": {
          "type": "string"
        }
      },
      "required": [ "elementUId", "typeItemUId", "isAutoCollect", "isActive", "moduleUIdAutoCollect", "sortOrder", "attribute", "modifiedBy" ]
    },
    "PrivatePropertyEdgeProperty": {
      "type": "object",
      "properties": {
        "attribute": {
          "type": "string"
        },
        "edgeUId": {
          "type": "string"
        },
        "modifiedBy": {
          "type": "string"
        },
        "typeItemUId": {
          "type": "string"
        },
        "uId": {
          "type": "string"
        }
      },
      "required": [ "edgeUId", "modifiedBy", "typeItemUId", "attribute" ]
    },
    "PrivatePropertyEdge": {
      "type": "object",
      "properties": {
        "elementUId": {
          "type": "string"
        },
        "isElementDriver": {
          "type": "boolean"
        },
        "modifiedBy": {
          "type": "string"
        },
        "privatePropertyEdgeProperties": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PrivatePropertyEdgeProperty"
          }
        },
        "privatePropertyUId": {
          "type": "string"
        },
        "typeItemUId": {
          "type": "string"
        }
      },
      "required": [ "elementUId", "privatePropertyUId", "isElementDriver", "modifiedBy", "typeItemUId" ]
    },
    "PrivatePropertyKey": {
      "type": "object",
      "properties": {
        "elementUId": {
          "type": "string"
        },
        "isAutoCollect": {
          "type": "boolean"
        },
        "isActive": {
          "type": "boolean"
        },
        "modifiedBy": {
          "type": "string"
        },
        "moduleUIdAutoCollect": {
          "type": "string"
        },
        "parentUId": {
          "type": "string"
        },
        "sortOrder": {
          "type": "integer"
        },
        "typeKeyUId": {
          "type": "string"
        },
        "typeUnitUId": {
          "type": "string"
        },
        "typeValueUId": {
          "type": "string"
        },
        "uId": {
          "type": "string"
        }
      },
      "required": [ "isAutoCollect", "isActive", "moduleUIdAutoCollect", "sortOrder", "elementUId", "typeKeyUId", "typeValueUId", "typeUnitUId", "modifiedBy" ]
    },
    "PrivateProperty": {
      "type": "object",
      "properties": {
        "attribute": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "modifiedBy": {
          "type": "string"
        },
        "parentUId": {
          "type": "string"
        },
        "privatePropertyKeyUId": {
          "type": "string"
        },
        "sortOrder": {
          "type": "integer"
        },
        "uId": {
          "type": "string"
        }
      },
      "required": [ "privatePropertyKeyUId", "sortOrder", "attribute", "isActive", "modifiedBy" ]
    }
  }
}

=== alexmsomarriba/TB-Syntosa-Validation/SyntosaJsonModels/PermissionModel.json
{
  "alias": "",
  "description": "The permission elment for roles that can manage teams.",
  "domainUId": "f8946341-01c5-4865-aa68-f41899aa63e5",
  "isActive": true,
  "isAutoCollect": false,
  "isBuiltIn": false,
  "moduleUId": "b89d4d91-35e9-4dbf-92b1-39b7dce008dc",
  "moduleRecordUId": "f7a11c6d-4b0c-43e4-aa8e-198c046d740c",
  "modifiedBy": "alex@teambond.io",
  "name": "ManageTeam",
  "parentUId": "",
  "typeItemUId": "3e3ef2b0-e15f-42c8-8876-2058fbe8755d",
  "typeUIdRecordStatus": "a3fa3141-209b-4396-bb49-426033a0973e",
  "uId": "afeb2995-5c3b-4894-b3c0-80e4d7b91acf",
  "elementEdges": [
    {
      "edgeProperties": [
        {
          "attribute": "",
          "edgeTypeUId": "",
          "edgeUId": "",
          "modifiedBy": "",
          "Name": "",
          "typeItemUId": "",
          "uId": ""
        }
      ],
      "labelUId": "",
      "modifiedBy": "",
      "sourceElementUId": "",
      "targetElementUId": "",
      "typeItemUId": "",
      "UId": ""
    }
  ],
  "globalPropertyEdges": [
    {
      "elementUId": "",
      "globalPropertyEdgeProperties": [
        {
          "attribute": "",
          "edgeUId": "",
          "modifiedBy": "",
          "typeItemUId": "",
          "uId": ""
        }
      ],
      "globalPropertyUId": "",
      "isElementDriver": false,
      "modifiedBy": "",
      "typeItemUId": "",
      "uId": ""
    }
  ],
  "globalPropertyList": [
    {
      "attribute": "",
      "elementUId": "afeb2995-5c3b-4894-b3c0-80e4d7b91acf",
      "isAutoCollect": false,
      "isActive": true,
      "modifiedBy": "alex@teambond.io",
      "moduleUIdAutoCollect": "",
      "name": "",
      "sortOrder": 0,
      "typeItemUId": "9fe98512-148b-451a-bb18-f01208ad196e",
      "uId": ""
    }
  ],
  "privatePropertyEdges": [
    {
      "elementUId": "",
      "isElementDriver": false,
      "modifiedBy": "",
      "privatePropertyEdgeProperties": [
        {
          "attribute": "",
          "edgeUId": "",
          "modifiedBy": "",
          "typeItemUId": "",
          "uId": ""
        }
      ],
      "privatePropertyUId": "",
      "typeItemUId": "",
      "New item - 2": ""
    }
  ],
  "privatePropertyKeys": [],
  "privateProperties": []
}
