=== alexmsomarriba/TB-Syntosa-Validation/SyntosaJsonModels/TypeItem.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "description": "The type item for user elments",
            "id": 0,
            "isActive": true,
            "isBuiltIn": true,
            "modifiedBy": "alex@teambond.io",
            "name": "User",
            "sysEndTime": "9999-12-31 23:59:59.9999999",
            "sysStartTime": "2020-07-15 07:38:37.1928994",
            "uId": "7d5e6e8a-f562-479c-a808-9b3c5a8f9769",
            "isAssignable": true,
            "isAutoCollect": false,
            "isNotifiable": true,
            "isParentActive": false,
            "isTypeFunctionActive": true,
            "isRelational": true,
            "isKeyValue": false,
            "isInMemory": false,
            "isGraph": false,
            "isDocument": false,
            "isLedger": false,
            "isTimeSeries": false,
            "isSearch": false,
            "moduleUIdAutoCollect": "1357c174-6ebb-4009-a465-c396dea28ed8",
            "parentName": "",
            "parentUId": "",
            "sortOrder": 0,
            "typeFunctionModuleUId": "1357c174-6ebb-4009-a465-c396dea28ed8",
            "typeUnitName": "string",
            "typeUnitUId": "a232ba7f-2861-429d-8bbb-fe14f6c223e0",
            "uiExtensions": ""
        }
    ],
    "required": [
        "description",
        "id",
        "isActive",
        "isBuiltIn",
        "modifiedBy",
        "name",
        "sysEndTime",
        "sysStartTime",
        "uId",
        "isAssignable",
        "isAutoCollect",
        "isNotifiable",
        "isParentActive",
        "isTypeFunctionActive",
        "isRelational",
        "isKeyValue",
        "isInMemory",
        "isGraph",
        "isDocument",
        "isLedger",
        "isTimeSeries",
        "isSearch",
        "moduleUIdAutoCollect",
        "parentName",
        "parentUId",
        "sortOrder",
        "typeFunctionModuleUId",
        "typeUnitName",
        "typeUnitUId",
        "uiExtensions"
    ],
    "additionalProperties": true,
    "properties": {
        "description": {
            "$id": "#/properties/description",
            "type": "string",
            "title": "The description schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "The type item for user elments"
            ]
        },
        "id": {
            "$id": "#/properties/id",
            "type": "integer",
            "title": "The id schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                0
            ]
        },
        "isActive": {
            "$id": "#/properties/isActive",
            "type": "boolean",
            "title": "The isActive schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "isBuiltIn": {
            "$id": "#/properties/isBuiltIn",
            "type": "boolean",
            "title": "The isBuiltIn schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "modifiedBy": {
            "$id": "#/properties/modifiedBy",
            "type": "string",
            "title": "The modifiedBy schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "alex@teambond.io"
            ]
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "User"
            ]
        },
        "sysEndTime": {
            "$id": "#/properties/sysEndTime",
            "type": "string",
            "title": "The sysEndTime schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "9999-12-31 23:59:59.9999999"
            ]
        },
        "sysStartTime": {
            "$id": "#/properties/sysStartTime",
            "type": "string",
            "title": "The sysStartTime schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "2020-07-15 07:38:37.1928994"
            ]
        },
        "uId": {
            "$id": "#/properties/uId",
            "type": "string",
            "title": "The uId schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "7d5e6e8a-f562-479c-a808-9b3c5a8f9769"
            ]
        },
        "isAssignable": {
            "$id": "#/properties/isAssignable",
            "type": "boolean",
            "title": "The isAssignable schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "isAutoCollect": {
            "$id": "#/properties/isAutoCollect",
            "type": "boolean",
            "title": "The isAutoCollect schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isNotifiable": {
            "$id": "#/properties/isNotifiable",
            "type": "boolean",
            "title": "The isNotifiable schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "isParentActive": {
            "$id": "#/properties/isParentActive",
            "type": "boolean",
            "title": "The isParentActive schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isTypeFunctionActive": {
            "$id": "#/properties/isTypeFunctionActive",
            "type": "boolean",
            "title": "The isTypeFunctionActive schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "isRelational": {
            "$id": "#/properties/isRelational",
            "type": "boolean",
            "title": "The isRelational schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                true
            ]
        },
        "isKeyValue": {
            "$id": "#/properties/isKeyValue",
            "type": "boolean",
            "title": "The isKeyValue schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isInMemory": {
            "$id": "#/properties/isInMemory",
            "type": "boolean",
            "title": "The isInMemory schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isGraph": {
            "$id": "#/properties/isGraph",
            "type": "boolean",
            "title": "The isGraph schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isDocument": {
            "$id": "#/properties/isDocument",
            "type": "boolean",
            "title": "The isDocument schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isLedger": {
            "$id": "#/properties/isLedger",
            "type": "boolean",
            "title": "The isLedger schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isTimeSeries": {
            "$id": "#/properties/isTimeSeries",
            "type": "boolean",
            "title": "The isTimeSeries schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "isSearch": {
            "$id": "#/properties/isSearch",
            "type": "boolean",
            "title": "The isSearch schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "moduleUIdAutoCollect": {
            "$id": "#/properties/moduleUIdAutoCollect",
            "type": "string",
            "title": "The moduleUIdAutoCollect schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "1357c174-6ebb-4009-a465-c396dea28ed8"
            ]
        },
        "parentName": {
            "$id": "#/properties/parentName",
            "type": "string",
            "title": "The parentName schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                ""
            ]
        },
        "parentUId": {
            "$id": "#/properties/parentUId",
            "type": "string",
            "title": "The parentUId schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                ""
            ]
        },
        "sortOrder": {
            "$id": "#/properties/sortOrder",
            "type": "integer",
            "title": "The sortOrder schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                0
            ]
        },
        "typeFunctionModuleUId": {
            "$id": "#/properties/typeFunctionModuleUId",
            "type": "string",
            "title": "The typeFunctionModuleUId schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "1357c174-6ebb-4009-a465-c396dea28ed8"
            ]
        },
        "typeUnitName": {
            "$id": "#/properties/typeUnitName",
            "type": "string",
            "title": "The typeUnitName schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "string"
            ]
        },
        "typeUnitUId": {
            "$id": "#/properties/typeUnitUId",
            "type": "string",
            "title": "The typeUnitUId schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "a232ba7f-2861-429d-8bbb-fe14f6c223e0"
            ]
        },
        "uiExtensions": {
            "$id": "#/properties/uiExtensions",
            "type": "string",
            "title": "The uiExtensions schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                ""
            ]
        }
    }
}

=== alexmsomarriba/TB-Syntosa-Validation/SyntosaJsonModels/UserTypeItem.json
{
  "description": "The type item for user elments",
  "id": 0,
  "isActive": true,
  "isBuiltIn": true,
  "modifiedBy": "alex@teambond.io",
  "name": "User",
  "sysEndTime": "9999-12-31 23:59:59.9999999",
  "sysStartTime": "2020-07-15 07:38:37.1928994",
  "uId": "7d5e6e8a-f562-479c-a808-9b3c5a8f9769",
  "isAssignable": true,
  "isAutoCollect": false,
  "isNotifiable": true,
  "isParentActive": false,
  "isTypeFunctionActive": true,
  "isRelational": true,
  "isKeyValue": false,
  "isInMemory": false,
  "isGraph": false,
  "isDocument": false,
  "isLedger": false,
  "isTimeSeries": false,
  "isSearch": false,
  "moduleUIdAutoCollect": "1357c174-6ebb-4009-a465-c396dea28ed8",
  "parentName": "",
  "parentUId": "",
  "sortOrder": 0,
  "typeFunctionModuleUId": "1357c174-6ebb-4009-a465-c396dea28ed8",
  "typeUnitName": "string",
  "typeUnitUId": "a232ba7f-2861-429d-8bbb-fe14f6c223e0",
  "uiExtensions": ""
}
